# Generated by Django 4.0.6 on 2022-07-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historico_pontuacao',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historico_pontuacao',
            },
        ),
        migrations.CreateModel(
            name='tb_categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'tb_categoria',
            },
        ),
        migrations.CreateModel(
            name='tb_cliente',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=254)),
                ('bairro_endereco', models.CharField(max_length=254, verbose_name='Endereço')),
                ('fone', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('senha', models.CharField(max_length=254)),
                ('pontuacao', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'db_table': 'tb_cliente',
            },
        ),
        migrations.CreateModel(
            name='tb_empresa',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('fone', models.CharField(max_length=254)),
                ('bairro_endereco', models.CharField(max_length=254, verbose_name='Endereço')),
                ('senha', models.CharField(max_length=254)),
                ('setor', models.CharField(max_length=254)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'db_table': 'tb_empresa',
            },
        ),
        migrations.CreateModel(
            name='tb_grupo',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_bairro', models.CharField(max_length=254)),
                ('cod_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashtoyou.tb_empresa')),
            ],
            options={
                'db_table': 'tb_grupo',
            },
        ),
        migrations.CreateModel(
            name='tb_cliente_empresa',
            fields=[
                ('codigo_clienteempresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashtoyou.tb_cliente')),
                ('cod_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashtoyou.tb_empresa')),
            ],
            options={
                'db_table': 'tb_cliente_empresa',
            },
        ),
        migrations.AddConstraint(
            model_name='tb_cliente_empresa',
            constraint=models.UniqueConstraint(fields=('cod_empresa', 'cod_cliente'), name='unique_cod_empresa_cod_cliente_combination'),
        ),
    ]
